### ISSUE TITLE
[Front] 레이아웃 설계

### ISSUE THREAD

**Issue by heasun0111** [seed-kau/Gecko#1]

**Comment by tmdrud7766** [comment]
```


플렉스를 이용하여 레이아웃을 구현해봄.

화면을 늘리고 줄이면 크기에 따라 조정가능하고 최소 픽셀을 맞추어서 제일 작은 화면이 고정되게 구현함 .

하지만 콘텐츠 부분에서 뭘 삽입해야서 내가원하는 2x2 or 2x3 을 구현 하기는 실패.

부족한점 : 레이아웃 이해도 콘텐츠부분에서 구역을 못나누겠음.

에를 들어 음식월드컵할때 사진을 나누고 선택하는 코드를 보았지만 해석실패 flex를 사용하지 않은 듯.
<img width="1324" alt="스크린샷 2019-07-07 오전 10 54 50" src="https://user-images.githubusercontent.com/48707838/60763067-8bfb5e00-a0a7-11e9-8fee-5e87a3f68af8.png">
<img width="1026" alt="스크린샷 2019-07-07 오전 10 59 04" src="https://user-images.githubusercontent.com/48707838/60763074-c533ce00-a0a7-11e9-8482-fdc9ad89adf0.png">

**Comment by heasun0111** [comment]
grid를 이용하여 레이아웃 설계를 하였음
설계 중 display:inline; 을 신경쓰지 않아서 에러가 발생했었다.

<중간 레이아웃 설계 결과물>
![image](https://user-images.githubusercontent.com/48648940/60834324-7139fe00-a1fb-11e9-854a-006c437be06a.png)

**Comment by Danpatpang** [comment]
@tmdrud7766 @heasun0111 서비스의 대략적인 디자인을 공유해주세요!
아직까지 메인 페이지의 모습이 잘 그려지지 않네요.😮

아래의 예시를 참고하여 공유해주시면 감사하겠습니다!
![image](https://user-images.githubusercontent.com/19412222/60835167-6bddb300-a1fd-11e9-819d-946579bd3631.png)

**Comment by tmdrud7766** [comment]
메인페이지부터 그리겠습니다

**Comment by heasun0111** [comment]
@Danpatpang
예시를 참고하여 작성한 대략적인 디자인 입니다. 혹시 추가할 내용이나 수정 사항 및 의문이 생기는 부분은 알려주세요!
![image](https://user-images.githubusercontent.com/48648940/61186847-1134d300-a6a5-11e9-8231-9e267483a6f9.png)

**Comment by heasun0111** [comment]
그리고 추가적으로 1page 레이아웃을 설계한 중간단계 결과물입니다.
![image](https://user-images.githubusercontent.com/48648940/61186930-2e1dd600-a6a6-11e9-9755-d071a95874cc.png)

이미지의 크기가 일정하지 않게 배열이 되는데, 문제점이 해결되면 다시 수정해서 올리겠습니다!
