### ISSUE TITLE
[Front] 레이아웃 기본틀 제작

### ISSUE THREAD

**Issue by tmdrud7766** [seed-kau/Gecko#3]
```
html 코드 

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>layout</title>
    <link rel="stylesheet"  href="laoyout.css">
  </head>
<body>
 <div class="container">
   <header>
     <h1>레이아웃 시행판</h1>
   </header>

   <section>
     <nav>
       <ul>
         <li>layout</li>
         <li>layout</li>



       </ul>
     </nav>
     <main>
레이아웃 사이즈 조절한것레이아웃 사이즈 조절한것레이아웃 사이즈 조절한것레이아웃 사이즈 조절한것레이아웃 사이즈 조절한것레이아웃 사이즈 조절한것레이아웃 사이즈 조절한것레이아웃 사이즈 조절한것레이아웃 사이즈 조절한것레이아웃 사이즈 조절한것레이아웃 사이즈 조절한것레이아웃 사이즈 조절한것레이아웃 사이즈 조절한것레이아웃 사이즈 조절한것레이아웃 사이즈 조절한것

     </main>
     <aside>

       그림넣을곳
     </aside>



   </section>
   <footer>
     <a href="www.naver.com"= 네이 </a>
   </footer>
 <div>
</body>
</html>
```

<img width="112" alt="스크린샷 2019-07-05 오후 5 15 22" src="https://user-images.githubusercontent.com/48707838/60763104-4ee39b80-a0a8-11e9-9a74-676c94f039cd.png">
<img width="646" alt="스크린샷 2019-07-06 오후 5 07 24" src="https://user-images.githubusercontent.com/48707838/60763110-691d7980-a0a8-11e9-8a71-62d0290ce70b.png">

```
css
.container{
  display: flex;
  flex-direction: column;
  border: 1px solid grey;

}

header{
  border: 1px solid grey;
}

section{
  border: 1px solid grey;
  display: flex;
  flex-direction: row;
}

nav{
  border-right: 1px solid grey;
  flex-basis: 200px;
}


main{
  padding: 15px;

}

aside{
  border-left: 15px;
  flex-basis: 200px;
}
nav,aside{
  border-left: 1px solid grey;
  flex-basis: 200px;
}

footer{
  border: 1px solid grey;
  text-align: center;
  padding: 15px;
}

.columnblock{
  width: 100%;
  column-gap: 30px;
  column-count: 3;
  column-width: 280px;
}
```

플렉스를 이용하여 레이아웃을 구현해봄.

화면을 늘리고 줄이면 크기에 따라 조정가능하고 최소 픽셀을 맞추어서 제일 작은 화면이 고정되게 구현함 .

하지만 콘텐츠 부분에서 뭘 삽입해야서 내가원하는 2x2 or 2x3 을 구현 하기는 실패.

부족한점 : 레이아웃 이해도 콘텐츠부분에서 구역을 못나누겠음.

에를 들어 음식월드컵할때 사진을 나누고 선택하는 코드를 보았지만 해석실패 flex를 사용하지 않은 듯.
<img width="1324" alt="스크린샷 2019-07-07 오전 10 54 50" src="https://user-images.githubusercontent.com/48707838/60763067-8bfb5e00-a0a7-11e9-8fee-5e87a3f68af8.png">
<img width="1026" alt="스크린샷 2019-07-07 오전 10 59 04" src="https://user-images.githubusercontent.com/48707838/60763074-c533ce00-a0a7-11e9-8482-fdc9ad89adf0.png">

**Comment by Danpatpang** [comment]
#1 과 동일한 주제이므로 내용을 옮겨주시기 바랍니다.
소스 코드를 올리실 필요는 없습니다.
flex 보다는 표 속성 또는 position 속성을 사용해 보시길 바랍니다.
또한 이슈 등록 전 `Preview`를 클릭하여 미리 글을 확인해주세요.

**Comment by heasun0111** [comment]
제 생각에는 콘텐츠 부분을 2x2 / 2x3로 나누지 않고 3x2로 나누어도 기능 구현할 때는 지장이 없다고 생각이 됩니다. 따라서 footer부분을 3칸으로 나누면 될 것 같습니다.

**Comment by heasun0111** [comment]
![image](https://user-images.githubusercontent.com/48648940/60764574-70a04b00-a0c7-11e9-9ff7-a0c56b43a9ee.png)
저 또한 레이아웃을 따로 만드려고 했는데 grid-template-columns: 부분에서 오류가 생겨서 나중에는 tmdrud7766 께서 올린 코드를 수정해보았습니다.
저희 프로젝트는 이미지를 업로드 해야하는 부분이 있어서 1-2칸에 그 기능을 구현했으며, footer부분에 링크를 올렸으나 제대로 구현이 되지 않아서 1-3칸에 링크를 구현해보았습니다. 추후에 표 속성, position 속성을 사용하여 문제점을 해결한 뒤 다시 올리겠습니다.
